### ISSUE TITLE
Visual studio code should depend on cups

### ISSUE THREAD

**Issue by nikobockerman** [funkill/fuverlay#2]
Hi,

I tried installing visual-studio-code package from your overlay. Installation worked well, but the application failed to launch because libcups.so.2 didn't exist.

`$ visual-studio-code 
visual-studio-code: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory`

Adding cups as runtime dependency fixed this issue for me. Attached a patch to the ebuild with the fix I applied.

[visual-studio-code-cups-dependency.patch.txt](https://github.com/funkill/fuverlay/files/222781/visual-studio-code-cups-dependency.patch.txt)

**Comment by funkill** [comment]
Ebuild fixed 987f17947c1c6d0e70f7592c4ae2587084fc6529
Thank you!
